# Generated by Django 2.1.5 on 2019-01-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=200)),
                ('flightNumber', models.CharField(max_length=200)),
                ('arrivalTime', models.CharField(max_length=200)),
                ('departureTime', models.CharField(max_length=200)),
                ('arrivalAirport', models.CharField(max_length=200)),
                ('departureAirport', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('flightCheck', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hydraulicMachine', models.BooleanField(default=True)),
                ('wheelsCheck', models.BooleanField(default=True)),
                ('landingMech', models.BooleanField(default=True)),
                ('navigationSystem', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, null=True)),
                ('lname', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('checkedBags', models.IntegerField()),
                ('classType', models.CharField(max_length=100)),
                ('specialPreference', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lastMileApp.Passenger'),
        ),
    ]
