# Generated by Django 2.1.5 on 2019-01-25 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastMileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrivalDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='departureDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
