# Generated by Django 2.1.5 on 2019-01-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastMileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingRef',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightcheck',
            name='flightNumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
