# Generated by Django 2.1.5 on 2019-01-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastMileApp', '0002_auto_20190125_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrivalDate',
            new_name='arrival',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departureDate',
            new_name='departure',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrivalTime',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departureTime',
        ),
    ]
