# Generated by Django 2.1.5 on 2019-01-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastMileApp', '0003_auto_20190126_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='maxSeats',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
