# Generated by Django 2.1.5 on 2019-01-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastMileApp', '0003_auto_20190125_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='id',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passenger_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phoneNumber',
            field=models.CharField(max_length=200),
        ),
    ]
