# Generated by Django 2.1.5 on 2019-01-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lastMileApp', '0004_flight_maxseats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='maxSeats',
            new_name='emptySeats',
        ),
    ]
