# Generated by Django 2.1.5 on 2019-01-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastMileApp', '0004_auto_20190125_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='bookingRef',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
